### ISSUE TITLE
NameError: name 'logger' is not defined

### ISSUE THREAD

**Issue by MaQingya** [Open-Debin/Emotion-FAN#26]
CUDA_VISIBLE_DEVICES=1 python baseline_ck_plus.py --fold 10
1.2.0
22-Apr-2021-10-17-35 --- args ---
baseline ck+ dataset, learning rate: 0.1
Traceback (most recent call last):
  File "baseline_ck_plus.py", line 155, in <module>
    main()
  File "baseline_ck_plus.py", line 45, in main
    train(train_loader, model, optimizer, epoch)
  File "baseline_ck_plus.py", line 91, in train
    logger.print('Epoch: [{:3d}][{:3d}/{:3d}]\t'
NameError: name 'logger' is not defined
When I look at line 22:  logger = util.Logger('./log/','baseline_ckplus')
What's this ?

**Comment by hqn19971113** [comment]
顶！同样的问题

**Comment by hqn19971113** [comment]
兄弟，他在train和main里面少传了个logger的参数
在47，48行的train（train_loader,model,optimizer,epoch,**logger**）
在62行def train（train_loader,model,optimizer,epoch,**logger**）
114行也在后面加个logger

**Comment by Open-Debin** [comment]
> logger

thanks for your explanation.

**Comment by Tina-xiao** [comment]
> 

谢谢！
